### ISSUE TITLE
Qvitter-free version?

### ISSUE THREAD

**Issue by sigmap** [mitchellurgero/armadillo#4]
Is there a way to make this without needing to qvitter? Even as a slightly downgraded gnusocial theme?

**Comment by mitchellurgero** [comment]
No - Right now that is not possible - You can however in config.php change:

```
$config['site']['qvitter']['enabledbydefault'] = true;
```

to

```
$config['site']['qvitter']['enabledbydefault'] = false;
```

To disable Qvitter by default.
